### ISSUE TITLE
Can't view stats (Grey screen)

### ISSUE THREAD

**Issue by burakdede0** [Ahmedazim7804/traktstats_app#2]
I have tried importing all-time-stats.json that I have generated but stats after "All Time Totals" section isn't showing up.

I thought the issue might be causing by non-English letters and tried replacing all non-English letters with English ones. Didn't fix the issue.

![Screenshot_20240104-125357](https://github.com/Ahmedazim7804/traktstats_app/assets/29973158/2cb19de5-428c-42dd-b6f0-6ff4f428f33a)

Tried with:
 - Nothing Phone 2 - Android 14
 - Xiaomi Mi A2 Lite - Android 13

**Comment by Ahmedazim7804** [comment]
for now, i have no logging system in the app. so i cannot debug through logs, can your share your particular `all-time-stats.json` if you don't mind.

**Comment by burakdede0** [comment]
Would be better if I can send it as private. Can you share your Telegram ID or email?

**Comment by Ahmedazim7804** [comment]
yes sure, you can send the email to `et8yoysr@anonaddy.me` address

**Comment by Ahmedazim7804** [comment]
Hi, the problem actually was the empty logo in first_play section, i have pushed a commit, and updated the app.
please try the latest version, the problem should be fixed.

**Comment by burakdede0** [comment]
Just updated, it is fixed now. Thanks.
