### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by simsinght** [Ahmedazim7804/traktstats_app#3]
i don't see it as part of the readme, and i'm unfamiliar with this project strucutre.

how do i run this app? or is it hosted somewhere?

**Comment by Ahmedazim7804** [comment]
oh this app is just a frontend, you first have to generate `all-time-stats.json` file using this [repo](https://github.com/Ahmedazim7804/trakt_vip_stats). Then select that file in the app.

**Comment by simsinght** [comment]
right i understand that. i have generated the json file but i don't know how to instantiate the app

**Comment by Ahmedazim7804** [comment]
well you can transfer that file to your phone and select the json file in app on the starting page, like the option shown in this [page](https://github.com/Ahmedazim7804/traktstats_app/blob/master/screenshots%2F1.png).

**Comment by simsinght** [comment]
does this app exist on the app store?

**Comment by Ahmedazim7804** [comment]
apple app store? no, it's kind of a niche app, also i do not have dev account of google or apple to publish app. and i am not familiar with f-droid publishing process to put it on f-droid.

**Comment by simsinght** [comment]
right so there's no downloading the app..

so how do i run the app?

**Comment by simsinght** [comment]
hmm i now see an apk under releases. i'm guessing that could be used to install onto an android phone

unfortunately i only have access to an iOS device and my laptop. 

is there a way to get the web version of this running?

**Comment by simsinght** [comment]
given it's just a front end app, github pages could've been a good host/use case

**Comment by Ahmedazim7804** [comment]
Yes you can install the apk on any android device.

Unfortunately i do not have access to a Mac, which is required to build app for iPhone or Mac.

if you can setup flutter, vscode and xcode (needed for mac i think), it is easy to build the app from source.

and as for web, i have not yet hosted the app.

**Comment by Ahmedazim7804** [comment]
> given it's just a front end app, github pages could've been a good host/use case

Github pages can host only static web page. but this app need to fetch images of movies, actors on runtime.
But i will look into it, it might work.

**Comment by simsinght** [comment]
i see. once i have flutter/vscode setup, will i be able to run in browser?

hmm seems like a pain all around. i'll try to just run an android emulator. feel free to resolve this. thanks for engaging

**Comment by simsinght** [comment]
> Github pages can host only static web page. but this app need to fetch images of movies, actors on runtime.
> But i will look into it, it might work.

yeah if the fetching doesn't require any api keys the browser will still fetch them fine

**Comment by Ahmedazim7804** [comment]
I have hosted the app on netlify for now, you can access it [here](https://traktstats.netlify.app/).
Although the app and its layout is not yet optimized for web (large screen).
